import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
// import { NavMenu } from '@/components/core/header/nav-menu'

import Footer from '@/components/core/footer';
import Header from '@/components/core/header';
import ShortcutNavigation from '@/components/core/shortcut-navigation';
import ClientI18nProvider from '@/components/ClientI18nProvider';
import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientI18nProvider locale={locale}>
          <Header locale={locale} />
          {children}

          <ShortcutNavigation locale={locale} />
          <Footer locale={locale} />
        </ClientI18nProvider>
      </body>
    </html>
  );
}
