import type { Metadata } from 'next';

// import { NavMenu } from '@/components/core/header/nav-menu'

import Footer from '@/components/core/footer';
import Header from '@/components/core/header';
import ShortcutNavigation from '@/components/core/shortcut-navigation';
import ClientI18nProvider from '@/components/ClientI18nProvider';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = params;
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`antialiased`}
      >
        <ClientI18nProvider locale={locale}>
          <Header locale={locale} />
          {children}

          <ShortcutNavigation locale={locale} />
          <Footer locale={locale} />
        </ClientI18nProvider>
      </body>
    </html>
  );
}

